// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rpccello

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CelloClient is the client API for Cello service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CelloClient interface {
	Cello(ctx context.Context, in *ReqCello, opts ...grpc.CallOption) (*ResCello, error)
}

type celloClient struct {
	cc grpc.ClientConnInterface
}

func NewCelloClient(cc grpc.ClientConnInterface) CelloClient {
	return &celloClient{cc}
}

func (c *celloClient) Cello(ctx context.Context, in *ReqCello, opts ...grpc.CallOption) (*ResCello, error) {
	out := new(ResCello)
	err := c.cc.Invoke(ctx, "/RpcCello.Cello/Cello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CelloServer is the server API for Cello service.
// All implementations must embed UnimplementedCelloServer
// for forward compatibility
type CelloServer interface {
	Cello(context.Context, *ReqCello) (*ResCello, error)
	mustEmbedUnimplementedCelloServer()
}

// UnimplementedCelloServer must be embedded to have forward compatible implementations.
type UnimplementedCelloServer struct {
}

func (*UnimplementedCelloServer) Cello(context.Context, *ReqCello) (*ResCello, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cello not implemented")
}
func (*UnimplementedCelloServer) mustEmbedUnimplementedCelloServer() {}

func RegisterCelloServer(s *grpc.Server, srv CelloServer) {
	s.RegisterService(&_Cello_serviceDesc, srv)
}

func _Cello_Cello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqCello)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CelloServer).Cello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RpcCello.Cello/Cello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CelloServer).Cello(ctx, req.(*ReqCello))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cello_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RpcCello.Cello",
	HandlerType: (*CelloServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Cello",
			Handler:    _Cello_Cello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "cello.proto",
}
