stages:
    - init
    - test
    - build
    - run

before_script:
    - export GOROOT="/usr/local/go"
    - export GOPATH="/home/gitlab-runner/go"
    - export PATH="$PATH:$GOROOT/bin:$GOPATH/bin"
    - export GOPROXY=direct
    - export Branch_Name="$CI_COMMIT_REF_NAME"
    - export Serivce_Name="flute"
    - export Build_Path="/home/gitlab-runner/tmp_build"
    - go mod vendor

copy_dir:
    stage: init
    script:
    - make copy_dir
    - ln -sf $GOPATH/src/hcc/pb ../pb
    - ln -sf $GOPATH/src/hcc/hcc_errors ../hcc_errors

unit_tests:
  stage: test
  script:
    - make test

race_detector:
  stage: test
  script:
    - make race

code_coverage:
  stage: test
  script:
    - make coverage
#  only:
#  - master

go_report:
  stage: test
  script:
    - make goreport
#  only:
#  - master

#lint_code:
#  stage: test
#  script:
#    - gmake lint_dep
#    - gmake lint

build:
  stage: build
  script:
    - make
    - if [[ ! -d "$Build_Path/$Serivce_Name/$Branch_Name" ]]; then mkdir -p $Build_Path/$Serivce_Name/$Branch_Name;fi
    - cp -f $PWD/$Serivce_Name $Build_Path/$Serivce_Name/$Branch_Name/
    - echo "Build Complete"

service_run:
  stage: run
  script:
    - sudo /usr/sbin/service $Serivce_Name stop
    - sudo cp $Build_Path/$Serivce_Name/$Branch_Name/$Serivce_Name /usr/local/bin/$Serivce_Name
    - sudo chmod 755 /usr/local/bin/$Serivce_Name
    - sudo /usr/sbin/service $Serivce_Name start
    - sudo rm -rf $Build_Path/$Serivce_Name/$Branch_Name
    - echo "Finished"
  only:
    - master
    - feature/dev