// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package rpcviolin_scheduler

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// SchedulerClient is the client API for Scheduler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SchedulerClient interface {
	ScheduleHandler(ctx context.Context, in *ReqScheduleHandler, opts ...grpc.CallOption) (*ResScheduleHandler, error)
}

type schedulerClient struct {
	cc grpc.ClientConnInterface
}

func NewSchedulerClient(cc grpc.ClientConnInterface) SchedulerClient {
	return &schedulerClient{cc}
}

func (c *schedulerClient) ScheduleHandler(ctx context.Context, in *ReqScheduleHandler, opts ...grpc.CallOption) (*ResScheduleHandler, error) {
	out := new(ResScheduleHandler)
	err := c.cc.Invoke(ctx, "/RpcScheduler.Scheduler/ScheduleHandler", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SchedulerServer is the server API for Scheduler service.
// All implementations must embed UnimplementedSchedulerServer
// for forward compatibility
type SchedulerServer interface {
	ScheduleHandler(context.Context, *ReqScheduleHandler) (*ResScheduleHandler, error)
	mustEmbedUnimplementedSchedulerServer()
}

// UnimplementedSchedulerServer must be embedded to have forward compatible implementations.
type UnimplementedSchedulerServer struct {
}

func (*UnimplementedSchedulerServer) ScheduleHandler(context.Context, *ReqScheduleHandler) (*ResScheduleHandler, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ScheduleHandler not implemented")
}
func (*UnimplementedSchedulerServer) mustEmbedUnimplementedSchedulerServer() {}

func RegisterSchedulerServer(s *grpc.Server, srv SchedulerServer) {
	s.RegisterService(&_Scheduler_serviceDesc, srv)
}

func _Scheduler_ScheduleHandler_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReqScheduleHandler)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SchedulerServer).ScheduleHandler(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/RpcScheduler.Scheduler/ScheduleHandler",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SchedulerServer).ScheduleHandler(ctx, req.(*ReqScheduleHandler))
	}
	return interceptor(ctx, in, info, handler)
}

var _Scheduler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "RpcScheduler.Scheduler",
	HandlerType: (*SchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ScheduleHandler",
			Handler:    _Scheduler_ScheduleHandler_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "violin_scheduler.proto",
}
