// Copyright 2020 by ish.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v4.0.0
// source: piccolo.proto

package rpcpiccolo

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	rpcmsgType "hcc/flute/action/grpc/pb/rpcmsgType"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

// Symbols defined in public import of msgType.proto.

type Empty = rpcmsgType.Empty
type HccError = rpcmsgType.HccError
type Node = rpcmsgType.Node
type NodeDetail = rpcmsgType.NodeDetail
type Server = rpcmsgType.Server
type ServerNode = rpcmsgType.ServerNode
type Quota = rpcmsgType.Quota
type VNC = rpcmsgType.VNC
type Volume = rpcmsgType.Volume
type VolumeAttachment = rpcmsgType.VolumeAttachment
type Pool = rpcmsgType.Pool
type AdaptiveIPSetting = rpcmsgType.AdaptiveIPSetting
type AdaptiveIPAvailableIPList = rpcmsgType.AdaptiveIPAvailableIPList
type AdaptiveIPServer = rpcmsgType.AdaptiveIPServer
type Subnet = rpcmsgType.Subnet
type Series = rpcmsgType.Series
type MetricInfo = rpcmsgType.MetricInfo
type MonitoringData = rpcmsgType.MonitoringData
type NormalAction = rpcmsgType.NormalAction
type HccAction = rpcmsgType.HccAction
type Action = rpcmsgType.Action
type Control = rpcmsgType.Control
type Controls = rpcmsgType.Controls
type ScheduledNodes = rpcmsgType.ScheduledNodes
type ScheduleServer = rpcmsgType.ScheduleServer
type ServerAction = rpcmsgType.ServerAction

type ReqWriteServerAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerUUID   string                   `protobuf:"bytes,1,opt,name=serverUUID,proto3" json:"serverUUID,omitempty"`
	ServerAction *rpcmsgType.ServerAction `protobuf:"bytes,2,opt,name=server_action,json=serverAction,proto3" json:"server_action,omitempty"`
}

func (x *ReqWriteServerAction) Reset() {
	*x = ReqWriteServerAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_piccolo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReqWriteServerAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqWriteServerAction) ProtoMessage() {}

func (x *ReqWriteServerAction) ProtoReflect() protoreflect.Message {
	mi := &file_piccolo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqWriteServerAction.ProtoReflect.Descriptor instead.
func (*ReqWriteServerAction) Descriptor() ([]byte, []int) {
	return file_piccolo_proto_rawDescGZIP(), []int{0}
}

func (x *ReqWriteServerAction) GetServerUUID() string {
	if x != nil {
		return x.ServerUUID
	}
	return ""
}

func (x *ReqWriteServerAction) GetServerAction() *rpcmsgType.ServerAction {
	if x != nil {
		return x.ServerAction
	}
	return nil
}

type ResWriteServerAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Result string `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (x *ResWriteServerAction) Reset() {
	*x = ResWriteServerAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_piccolo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResWriteServerAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResWriteServerAction) ProtoMessage() {}

func (x *ResWriteServerAction) ProtoReflect() protoreflect.Message {
	mi := &file_piccolo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResWriteServerAction.ProtoReflect.Descriptor instead.
func (*ResWriteServerAction) Descriptor() ([]byte, []int) {
	return file_piccolo_proto_rawDescGZIP(), []int{1}
}

func (x *ResWriteServerAction) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

var File_piccolo_proto protoreflect.FileDescriptor

var file_piccolo_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x70, 0x69, 0x63, 0x63, 0x6f, 0x6c, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x52, 0x70, 0x63, 0x50, 0x69, 0x63, 0x63, 0x6f, 0x6c, 0x6f, 0x1a, 0x0d, 0x6d, 0x73, 0x67,
	0x54, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x72, 0x0a, 0x14, 0x52, 0x65,
	0x71, 0x57, 0x72, 0x69, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x55, 0x55, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x55, 0x55,
	0x49, 0x44, 0x12, 0x3a, 0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x5f, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x4d, 0x73, 0x67, 0x54,
	0x79, 0x70, 0x65, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x0c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x2e,
	0x0a, 0x14, 0x52, 0x65, 0x73, 0x57, 0x72, 0x69, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x64,
	0x0a, 0x07, 0x50, 0x69, 0x63, 0x63, 0x6f, 0x6c, 0x6f, 0x12, 0x59, 0x0a, 0x11, 0x57, 0x72, 0x69,
	0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x20,
	0x2e, 0x52, 0x70, 0x63, 0x50, 0x69, 0x63, 0x63, 0x6f, 0x6c, 0x6f, 0x2e, 0x52, 0x65, 0x71, 0x57,
	0x72, 0x69, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x1a, 0x20, 0x2e, 0x52, 0x70, 0x63, 0x50, 0x69, 0x63, 0x63, 0x6f, 0x6c, 0x6f, 0x2e, 0x52, 0x65,
	0x73, 0x57, 0x72, 0x69, 0x74, 0x65, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x22, 0x00, 0x42, 0x25, 0x5a, 0x23, 0x68, 0x63, 0x63, 0x2f, 0x66, 0x6c, 0x75, 0x74,
	0x65, 0x2f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62,
	0x2f, 0x72, 0x70, 0x63, 0x70, 0x69, 0x63, 0x63, 0x6f, 0x6c, 0x6f, 0x50, 0x00, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_piccolo_proto_rawDescOnce sync.Once
	file_piccolo_proto_rawDescData = file_piccolo_proto_rawDesc
)

func file_piccolo_proto_rawDescGZIP() []byte {
	file_piccolo_proto_rawDescOnce.Do(func() {
		file_piccolo_proto_rawDescData = protoimpl.X.CompressGZIP(file_piccolo_proto_rawDescData)
	})
	return file_piccolo_proto_rawDescData
}

var file_piccolo_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_piccolo_proto_goTypes = []interface{}{
	(*ReqWriteServerAction)(nil),    // 0: RpcPiccolo.ReqWriteServerAction
	(*ResWriteServerAction)(nil),    // 1: RpcPiccolo.ResWriteServerAction
	(*rpcmsgType.ServerAction)(nil), // 2: MsgType.ServerAction
}
var file_piccolo_proto_depIdxs = []int32{
	2, // 0: RpcPiccolo.ReqWriteServerAction.server_action:type_name -> MsgType.ServerAction
	0, // 1: RpcPiccolo.Piccolo.WriteServerAction:input_type -> RpcPiccolo.ReqWriteServerAction
	1, // 2: RpcPiccolo.Piccolo.WriteServerAction:output_type -> RpcPiccolo.ResWriteServerAction
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_piccolo_proto_init() }
func file_piccolo_proto_init() {
	if File_piccolo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_piccolo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReqWriteServerAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_piccolo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResWriteServerAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_piccolo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_piccolo_proto_goTypes,
		DependencyIndexes: file_piccolo_proto_depIdxs,
		MessageInfos:      file_piccolo_proto_msgTypes,
	}.Build()
	File_piccolo_proto = out.File
	file_piccolo_proto_rawDesc = nil
	file_piccolo_proto_goTypes = nil
	file_piccolo_proto_depIdxs = nil
}
